### ISSUE TITLE
It does not look like the models are initializing

### ISSUE THREAD

**Issue by powerspowers** [rahulbhalley/Progressive-Growing-of-GANs#5]
I am having trouble running pggan on a fresh install of pytorch on Windows 10. Get the following error:

>python pggan.py --ngpu 1 --train_data_root \Users\Powerpop\Desktop\pggan\wikiart\popart
Configuration
train_data_root: \Users\Powerpop\Desktop\pggan\wikiart\popart
random_seed: 1558492887
n_gpu: 8
lr: 0.001
lr_decay: 0.87
eps_drift: 0.001
smoothing: 0.997
nc: 3
nz: 512
ngf: 512
ndf: 512
TICK: 1000
max_resl: 9
trns_tick: 200
stab_tick: 100
flag_wn: True
flag_bn: False
flag_pixelwise: True
flag_gdrop: True
flag_leaky: True
flag_tanh: False
flag_sigmoid: False
flag_add_noise: True
flag_norm_latent: False
flag_add_drift: True
optimizer: adam
beta1: 0.0
beta2: 0.99
use_tb: True
save_img_every: 20
display_tb_every: 5
C:\Users\Powerpop\Desktop\pggan\custom_layers.py:114: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  kaiming_normal(self.conv.weight, a=calculate_gain('conv2d'))
Traceback (most recent call last):
  File "pggan.py", line 364, in <module>
    pggan = PGGAN(config)
  File "pggan.py", line 61, in __init__
    self.G = Generator(config)
  File "C:\Users\Powerpop\Desktop\pggan\network.py", line 88, in __init__
    self.model = self.get_init_gen()
  File "C:\Users\Powerpop\Desktop\pggan\network.py", line 136, in get_init_gen
    self.module_names = get_module_names(model)
  File "C:\Users\Powerpop\Desktop\pggan\network.py", line 66, in get_module_names
    for key, val in model.state_dict().iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

**Comment by powerspowers** [comment]
DOH - python3 changed iteritems to items
